apiVersion: apps/v1
kind: Deployment
metadata:
  name: vollmed
  labels:
    app: vollmed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vollmed
  template:
    metadata:
      labels:
        app: vollmed
    spec:
      containers:
      - name: vollmed-api
        image: titiura/vollmed:v1
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dados          
              key: DB_HOST
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: dados          
              key: DB_HOST
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: dados          
              key: DB_DATABASE
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: senhas          
              key: DB_PASSWORD
        # livenessProbe:
        #   httpGet:
        #     path: /paciente
        #     port: 3000
        #   initialDelaySeconds: 10
        #   periodSeconds: 3